// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ToyStore_API.Data;

#nullable disable

namespace ToyStore_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250325224102_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToyStore_API.Models.Toys", b =>
                {
                    b.Property<int>("Id_toy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_toy"));

                    b.Property<string>("Brand_toy")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<int>("Classification_toy")
                        .HasMaxLength(20)
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Name_toy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<decimal>("Price_toy")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Type_toy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.HasKey("Id_toy");

                    b.ToTable("TB_TOYS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
